//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VytHug.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_PROCESSVIEWER               100
#define IDS_TASKMGR                     100
#define IDS_FILEVIEWER                  101
#define IDS_ENTERPATH                   102
#define IDS_COLON                       103
#define IDS_LOOKOVER                    104
#define IDS_FILELIST                    105
#define IDS_FILEDETAIL                  106
#define IDS_FILENAME                    107
#define IDS_PATHABSOLUTE                108
#define IDS_FILEITEM                    109
#define IDS_FILEINFO                    110
#define IDS_CREATETIME                  111
#define IDS_YEAR                        112
#define IDS_MONTH                       113
#define IDS_DAY                         114
#define IDS_LASTVISITTIME               115
#define IDS_LASTMODIFYTIME              116
#define IDS_FILESIZE                    117
#define IDS_FILEATTRIBUTE               118
#define IDS_MD5                         119
#define IDS_NONE                        120
#define IDS_HIDE                        121
#define IDS_INSUFFICIENT_PERMISSIONS    122
#define IDS_ACCESS_FAILED               122
#define IDS_PID                         123
#define IDS_PROCESSPATH                 124
#define IDS_TID                         125
#define IDS_PRIORITY                    126
#define IDS_THREADSTATUS                127
#define IDR_MAINFRAME                   128
#define IDS_MODULENAME                  128
#define IDD_TM_FILEVIEWER               129
#define IDS_THREAD                      129
#define IDD_CLEANER                     129
#define IDD_TM_PROCESSVIEWER            130
#define IDS_MODULESIZE                  130
#define IDS_MODULEPATH                  131
#define IDS_HID                         132
#define IDS_HEAPSIZE                    133
#define IDD_DIALOG1                     133
#define IDD_TEDIOUS                     133
#define IDS_HEAPIMAGE                   134
#define IDD_TA_PROCESSINFO              135
#define IDS_HEAPSTATUS                  135
#define IDD_DIALOG2                     135
#define IDD_TA_PROCESS                  135
#define IDD_TA_MODULE                   136
#define IDS_MODULE                      136
#define IDD_TA_THREAD                   137
#define IDS_HEAP                        137
#define IDR_TA_TRACKMENU                137
#define IDS_THREADRUNNING               138
#define IDS_THREADSUSPENDED             139
#define IDR_SE_TRACKMENU                139
#define IDS_HEAP_USED                   140
#define IDR_SO_TRACKMENU                140
#define IDR_TM_TRACKMENU                141
#define IDS_HEAP_MOVEABLE               141
#define IDS_HEAP_FREE                   142
#define IDD_TA_HEAP                     143
#define IDS_TERMINATEP_FAILED           143
#define IDS_TERMINATET_FAILED           144
#define IDS_SUSPEND_FAILED              145
#define IDS_RESUME_FAILED               146
#define IDS_CPU                         147
#define IDS_MEMORY                      148
#define IDS_ABOUTBOX                    149
#define IDS_CLEANER                     150
#define IDS_PATHHINT                    151
#define IDS_CL_SCANSYS                  152
#define IDS_CL_SCANEXP                  153
#define IDS_CL_DROPTRASH                154
#define IDS_CL_VIEWPATH                 155
#define IDS_CL_INFOLIST                 156
#define IDS_CL_HELPTEXT                 157
#define IDS_DIRECTORY                   158
#define IDS_FILE                        159
#define IDS_ANTIVIRUS                   160
#define IDS_SOFTMGR                     161
#define IDS_SERVICEMGR                  162
#define IDS_WINDOWMGR                   163
#define IDS_PELOADER                    164
#define IDS_TEDIOUS                     165
#define IDS_NAME                        166
#define IDS_DESCRIPTION                 167
#define IDS_STATUS                      168
#define IDS_SERVICE_TYPE                169
#define IDS_RUN_TYPE                    170
#define IDS_SUSPENDED                   171
#define IDS_RUNNING                     172
#define IDS_MANUAL                      173
#define IDS_AUTO                        174
#define IDS_SERVICE_SHARED              175
#define IDS_SERVICE_SINGLE              176
#define IDS_TASK                        177
#define IDS_INSTALLTIME                 178
#define IDS_VERSION                     179
#define IDS_WINDOW_HANDLE               180
#define IDS_WINDOW_TITLE                181
#define IDS_WINDOW_CLASS                182
#define IDS_ORDER                       183
#define IDS_POSITION                    184
#define IDS_STOPPING                    185
#define IDS_STARTING                    186
#define IDS_CLOSEING                    187
#define IDS_CLOSED                      188
#define IDS_CONTINUING                  189
#define IDS_SERVICE_BOOT_START          190
#define IDS_INVALID                     191
#define IDS_SERVICE_SYSTEM_START        192
#define IDS_SERVICE_SYSTEM              193
#define IDS_SERVICE_DRIVER              194
#define IDD_ABOUTBOX                    200
#define IDD_TASKMANAGER_DIALOG          202
#define IDD_VYTHUG_DIALOG               302
#define IDD_SOFTWARE                    305
#define IDD_SERVICE                     306
#define IDD_WINDOWS                     307
#define IDD_TASKMANAGER                 308
#define IDD_PELOADER                    309
#define IDD_ANTIVIRUS                   310
#define IDC_TAB1                        1000
#define IDC_HOME_TAB                    1000
#define IDC_TAM_TAB                     1000
#define IDC_BUTTON1                     1001
#define IDC_CL_CLEANBUTTON              1001
#define IDC_BUTTON2                     1002
#define IDC_CL_FILETREE                 1002
#define IDC_BUTTON3                     1003
#define IDC_CL_FILELIST                 1003
#define IDC_BUTTON4                     1004
#define IDC_CL_CPUPROGRESS              1004
#define IDC_TE_DORMANT                  1004
#define IDC_BUTTON5                     1005
#define IDC_CL_MEMORYPROGRESS           1005
#define IDC_TE_LOCK                     1005
#define IDC_BUTTON6                     1006
#define IDC_CL_VIEWPATH                 1006
#define IDC_CL_VIEWPATHBUTTON           1006
#define IDC_TE_SLEEP                    1006
#define IDC_CL_PATHEDIT                 1007
#define IDC_CL_MD5                      1008
#define IDC_CL_SIZETEXT                 1009
#define IDC_CL_MTIMETEXT                1010
#define IDC_CL_MTIMEHINT                1011
#define IDC_CL_STIMETEXT                1012
#define IDC_CL_STIMEHINT                1013
#define IDC_CL_CTIMETEXT                1014
#define IDC_CL_CTIMEHINT                1015
#define IDC_CL_NAMETEXT                 1016
#define IDC_CL_TYPETEXT                 1017
#define IDC_CL_CPUTEXT                  1018
#define IDC_CL_MEMORYTEXT               1019
#define IDC_CL_PATHHINT                 1020
#define IDC_CL_SCANSYS                  1021
#define IDC_CL_SCANEXP                  1022
#define IDC_CL_DROPTRASH                1023
#define IDC_CL_INFOLIST                 1024
#define IDC_CL_HELPTEXT                 1025
#define IDC_PROGRESS1                   1026
#define IDC_TE_PROGRESSCPU              1026
#define IDC_PROGRESS2                   1027
#define IDC_TE_PROGRESSMEMORY           1027
#define IDC_LIST1                       1028
#define IDC_LIST2                       1030
#define IDC_RADIO1                      1031
#define IDC_RADIO2                      1032
#define IDC_RADIO3                      1033
#define IDC_RADIO4                      1034
#define IDC_SE_LIST                     1035
#define IDC_SO_LIST                     1036
#define IDC_WI_LIST                     1037
#define IDC_TA_LIST                     1038
#define IDC_TA_THREADS                  1039
#define IDC_TE_CPUTEXT                  1039
#define IDC_TA_MODULES                  1040
#define IDC_TE_MEMORYTEXT               1040
#define IDC_TA_HEAPS                    1041
#define IDC_TE_CLEANMEMORY              1041
#define IDC_TE_POWEROFF                 1042
#define IDC_TE_RESTART                  1043
#define IDC_TE_LOGOFF                   1044
#define IDC_TE_GROUPCPU                 1045
#define IDC_TE_GROUPMEMORY              1046
#define IDC_TE_POWERRAISING             1047
#define IDC_PE_LFANEW                   1047
#define IDC_PE_DIRBTN                   1048
#define IDC_PE_MACHINE                  1049
#define IDC_PE_SECTIONNUM               1050
#define IDC_PE_TIMESTAMP                1051
#define IDC_PE_OPHSIZE                  1052
#define IDC_PE_FILECHAR                 1053
#define IDC_PE_SECBTN                   1054
#define IDC_PE_MAGIC                    1059
#define IDC_PE_SECALIGN                 1060
#define IDC_PE_HEADERSIZE               1061
#define IDC_PE_DIRNUM                   1062
#define IDC_PE_RVAEDIT                  1063
#define IDC_PE_ENTRYPOINT               1067
#define IDC_PE_MAJORSUBSYS              1068
#define IDC_PE_FILESUBSYS               1069
#define IDC_PE_IMAGEBASE                1075
#define IDC_PE_IMAGESIZE                1076
#define IDC_PE_DLLCHAR                  1077
#define IDC_PE_FILEALIGN                1080
#define IDC_PE_VAEDIT                   1081
#define IDC_EDIT19                      1082
#define IDC_PE_FOA_EDIT                 1082
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_TAP_THREAD                   32782
#define ID_TAP_MODULE                   32783
#define ID_TAP_TERMINATE                32784
#define ID_TAP_REFRESH                  32785
#define ID_TAT_SUSPEND                  32786
#define ID_TAT_RESUME                   32787
#define ID_TAT_TERMINATE                32788
#define ID_SO_RUN                       32789
#define ID_SO_STOP                      32790
#define ID_SE_REFRESH                   32791
#define ID_SE_RUN                       32792
#define ID_SE_STOP                      32793
#define ID_SO_UNINSTALL                 32794
#define ID_SO_UPDATE                    32795
#define ID_SO_REFRESH                   32796
#define ID_SO_EXPLORER                  32797
#define ID_TAP_HEAP                     32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
